server {
    listen 80;
    server_name store.hendy.com;

    location /api/ {
        proxy_pass http://10.0.0.5:5000/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://10.0.0.4:3000/;
        proxy_set_header Host $host;
    }
}
