version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hendy_postgres
    restart: always
    environment:
      POSTGRES_USER: hendy_admin
      POSTGRES_PASSWORD: hendy_secure_password
      POSTGRES_DB: hendy_store
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: hendy_redis
    restart: always
    ports:
      - "6379:6379"

  clamav:
    image: clamav/clamav:latest
    container_name: hendy_clamav
    restart: always
    ports:
      - "3310:3310"
